<div class="slide">
<ul>
  <li>one测试1</li>
  <li>one测试2</li>
  <li>one测试3</li>
  <li>one测试4</li>
  <li>one测试5</li>
  <li>one测试6</li>
  <li>one测试7</li>
  <li>one测试8</li>
  <li>one测试9</li>
  <li>one测试10</li>
  <li>one测试11</li>
  <li>one测试12</li>
  <li>one测试13</li>
  <li>one测试14</li>
  <li>one测试15</li>
  <li>one测试16</li>
  <li>one测试17</li>
  <li>one测试18</li>
  <li>one测试19</li>
  <li>one测试20</li>
  <li>one测试21</li>
  <li>one测试22</li>
  <li>one测试23</li>
  <li>one测试24</li>
  <li>one测试25</li>
  <li>one测试26</li>
  <li>one测试27</li>
  <li>one测试28</li>
  <li>one测试</li>
  <li>one测试21</li>
  <li>one测试22</li>
  <li>one测试23</li>
  <li>one测试24</li>
  <li>one测试25</li>
  <li>one测试26</li>
  <li>one测试27</li>
  <li>one测试28</li>
  <li>one测试</li>
  <li>one测试21</li>
  <li>one测试22</li>
  <li>one测试23</li>
  <li>one测试24</li>
  <li>one测试25</li>
  <li>one测试26</li>
  <li>one测试27</li>
  <li>one测试28</li>
</ul>
</div>

